const countries = {
    "ta-IN": "Tamil",
    "en-GB": "English",   
    "hi-IN": "Hindi",
    "ml-IN": "Malayalam",
    "te-IN": "Telugu",
    "kn-IN": "Kannada",
    "zh-cn-CN": "Chinese",   
    "ko-KR": "Korean",
    "ar-SA": "Arabic",  
    "bn-IN": "Bengali",
    "de-DE": "German",
    "el-GR": "Greek", 
    "es-ES": "Spanish", 
    "fa-IR": "Persian",    
    "fr-FR": "French",   
    "gu-IN": "Gujarati",   
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ne-NP": "Nepali",   
    "ur-PK": "Pakistani",    
    "th-TH": "Thai",
    "tr-TR": "Turkish",
}